const data = [
  {
    id: 1,
    name: "Vania Propper",
    email: "vpropper0@joomla.org",
    job: "Teacher",
    twitter: "vpropper0",
  },
  {
    id: 2,
    name: "Shel Yegoshin",
    email: "syegoshin1@github.com",
    job: "Physical Therapy Assistant",
    twitter: "syegoshin1",
  },
  {
    id: 3,
    name: "Terrell Casey",
    email: "tcasey2@instagram.com",
    job: "Paralegal",
    twitter: "tcasey2",
  },
  {
    id: 4,
    name: "Zechariah Kobel",
    email: "zkobel3@slideshare.net",
    job: "Sales Associate",
    twitter: "zkobel3",
  },
  {
    id: 5,
    name: "Brigg Stidever",
    email: "bstidever4@moonfruit.com",
    job: "Geological Engineer",
    twitter: "bstidever4",
  },
  {
    id: 6,
    name: "Verile Deabill",
    email: "vdeabill5@sun.com",
    job: "General Manager",
    twitter: "vdeabill5",
  },
  {
    id: 7,
    name: "Chancey Hekkert",
    email: "chekkert6@twitpic.com",
    job: "Executive Secretary",
    twitter: "chekkert6",
  },
  {
    id: 8,
    name: "Lane Hammersley",
    email: "lhammersley7@dagondesign.com",
    job: "Software Engineer I",
    twitter: "lhammersley7",
  },
  {
    id: 9,
    name: "Xymenes Klaussen",
    email: "xklaussen8@mapquest.com",
    job: "Data Coordiator",
    twitter: "xklaussen8",
  },
  {
    id: 10,
    name: "Tanitansy Crowley",
    email: "tcrowley9@instagram.com",
    job: "Database Administrator II",
    twitter: "tcrowley9",
  },
];
